name: example
duration: 10
network:
  - traffic_control: true
    bandwidth: 1mbit
    limit: 1250
    burst: 6250
    delay: 100000
    duration: 10
applications:
  - name: server
    namespace: ns1
    start_time: 0
    duration: 10
    environment: []
    binary: iperf3
    arguments:
      - '-s'
      - '--logfile'
      - 'server.log'
  - name: client
    namespace: ns4
    start_time: 0
    duration: 10
    environment: []
    binary: iperf3
    arguments:
      - '-c'
      - '10.1.0.10'
      - '--logfile'
      - 'client.log'
      - '-i'
      - '0.1'
      - '-u'
      - '-b'
      - '1M'
